### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by innerspirit** [sgerhardt/TakeStock#2]
Looks like that webservicex thing has been down for a while, I keep getting No Data Found for all tickers.

Any alternatives?

**Comment by sgerhardt** [comment]
I've noticed it too. I've been disappointed with the flakey reliability of that web "service". I'll look for something else. If I can't find any web services or apis, I'll just parse a web page.

**Comment by sgerhardt** [comment]
I've made the update to fix the price issue. I'm grabbing it from NASDAQ's site now - which should be much more reliable as they run a pretty stable AWS setup from what I've read. https://github.com/sgerhardt/TakeStock/commit/71b00c627aa09a27fdf0ee7322139ae8aa3ab94a

**Comment by innerspirit** [comment]
It´s working great now, thanks for the quick response!
